-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BackendAPI.Object.Todo exposing (..)

import BackendAPI.InputObject
import BackendAPI.Interface
import BackendAPI.Object
import BackendAPI.Scalar
import BackendAPI.ScalarCodecs
import BackendAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


completed : SelectionSet Bool BackendAPI.Object.Todo
completed =
    Object.selectionForField "Bool" "completed" [] Decode.bool


created_at : SelectionSet (Maybe BackendAPI.ScalarCodecs.Timestamptz) BackendAPI.Object.Todo
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (BackendAPI.ScalarCodecs.codecs |> BackendAPI.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet Int BackendAPI.Object.Todo
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String BackendAPI.Object.Todo
name =
    Object.selectionForField "String" "name" [] Decode.string


updated_at : SelectionSet (Maybe BackendAPI.ScalarCodecs.Timestamptz) BackendAPI.Object.Todo
updated_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "updated_at" [] (BackendAPI.ScalarCodecs.codecs |> BackendAPI.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


{-| An object relationship
-}
user :
    SelectionSet decodesTo BackendAPI.Object.User
    -> SelectionSet decodesTo BackendAPI.Object.Todo
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity


user_id : SelectionSet Int BackendAPI.Object.Todo
user_id =
    Object.selectionForField "Int" "user_id" [] Decode.int
