-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BackendAPI.Enum.Todo_update_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "todo"

  - Name - column name

-}
type Todo_update_column
    = Name


list : List Todo_update_column
list =
    [ Name ]


decoder : Decoder Todo_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "name" ->
                        Decode.succeed Name

                    _ ->
                        Decode.fail ("Invalid Todo_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Todo_update_column -> String
toString enum____ =
    case enum____ of
        Name ->
            "name"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Todo_update_column
fromString enumString____ =
    case enumString____ of
        "name" ->
            Just Name

        _ ->
            Nothing
