-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BackendAPI.Enum.Todo_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "todo"

  - Todo\_pkey - unique or primary key constraint

-}
type Todo_constraint
    = Todo_pkey


list : List Todo_constraint
list =
    [ Todo_pkey ]


decoder : Decoder Todo_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "todo_pkey" ->
                        Decode.succeed Todo_pkey

                    _ ->
                        Decode.fail ("Invalid Todo_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Todo_constraint -> String
toString enum____ =
    case enum____ of
        Todo_pkey ->
            "todo_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Todo_constraint
fromString enumString____ =
    case enumString____ of
        "todo_pkey" ->
            Just Todo_pkey

        _ ->
            Nothing
