-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BackendAPI.Object exposing (..)


type Todo
    = Todo


type Todo_mutation_response
    = Todo_mutation_response


type User
    = User
