-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BackendAPI.ScalarCodecs exposing (..)

import BackendAPI.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Timestamptz =
    BackendAPI.Scalar.Timestamptz


codecs : BackendAPI.Scalar.Codecs Timestamptz
codecs =
    BackendAPI.Scalar.defineCodecs
        { codecTimestamptz = defaultCodecs.codecTimestamptz
        }
